### ISSUE TITLE
Box2d benchmark source?

### ISSUE THREAD

**Issue by rahulchaphalkar** [kripken/Massive#22]
Hi, this is a Question, not an issue.
The website says that the box2d benchmark is 'based' on bench2d. Can anyone confirm if it is exactly the same as bench2d, or if any changes have been made? Its hard to figure it out because of the minified version generated by emscripten, so it  would also help if someone can point to the c++ source / the non-minified version in js (if different from bench2d).
Thanks.

**Comment by kripken** [comment]
`driver.js` has a comment for how to rebuild each of the benchmarks. For box2d, looks like it says "let emscripten benchmark suite generate it for you". `tests/test_benchmark.py` in emscripten builds box2d and uses [`tests/box2d/Benchmark.cpp`](https://github.com/kripken/emscripten/blob/master/tests/box2d/Benchmark.cpp), which indeed has a comment "// Based on joelgwebber's Box2D benchmarks." It might be modified a little, though, so worth diffing the files.

**Comment by rahulchaphalkar** [comment]
Ah, thank you, that helped.
